# Generated by Django 5.0.4 on 2024-04-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("palette", "0002_remove_color_palette_colorinpalette_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="color",
            options={"verbose_name": "Цвет", "verbose_name_plural": "Цвета"},
        ),
        migrations.AlterModelOptions(
            name="colorinpalette",
            options={
                "ordering": ("palette",),
                "verbose_name": "Цвет в палитре",
                "verbose_name_plural": "Цвета в палитре",
            },
        ),
        migrations.AlterModelOptions(
            name="palette",
            options={"verbose_name": "Палитра", "verbose_name_plural": "Палитры"},
        ),
        migrations.AlterField(
            model_name="colorinpalette",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="palette.color",
                verbose_name="Цвет",
            ),
        ),
        migrations.AlterField(
            model_name="colorinpalette",
            name="palette",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color_list",
                to="palette.palette",
                verbose_name="Палитра",
            ),
        ),
    ]
