# Generated by Django 5.0.4 on 2024-04-17 17:03

import colorfield.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("palette", "0003_alter_color_options_alter_colorinpalette_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="hex",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=7,
                samples=None,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^#([0-9a-fA-F]{3,6})$")
                ],
                verbose_name="HEX code",
            ),
        ),
    ]
