# Generated by Django 5.0.4 on 2024-04-18 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("palette", "0004_alter_color_hex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="hex",
            field=models.CharField(
                max_length=7,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^#([0-9a-fA-F]{3,6})$")
                ],
                verbose_name="HEX code",
            ),
        ),
    ]
